- id: '1560560582904'
  alias: Lounge Light On
  trigger:
  - entity_id: switch.lounge
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Lounge Powered on
      title: '{{now().strftime(''%H:%M:%S'')}}'
    service: notify.mypush
- id: '1560560582905'
  alias: Lounge Light Off
  trigger:
  - entity_id: switch.lounge
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Lounge Powered off
      title: '{{now().strftime(''%H:%M:%S'')}}'
    service: notify.mypush
- id: '1560567442407'
  alias: Turn on light if sensor triggered
  trigger:
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    platform: state
    to: '8'
  condition: []
  action:
  - data:
      entity_id: switch.lounge
    service: switch.toggle
- id: '1560567442409'
  alias: Sensor auto 1
  trigger:
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    platform: state
    to: '3'
  condition: []
  action:
  - data:
      message: sensor alert 1
      title: '{{now().strftime(''%H:%M:%S'')}}'
    service: notify.mypush
- id: '1560590768985'
  alias: Motion
  trigger:
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_burglar
    platform: state
    to: '8'
  condition: []
  action:
  - data:
      message: sensor alert 1 changed to 8
      title: '{{now().strftime(''%H:%M:%S'')}}'
    service: notify.mypush
- id: '1560591428856'
  alias: Temp above 19.2
  trigger:
  - entity_id: sensor.aeon_labs_zw100_multisensor_6_temperature
    from: '19.2'
    platform: state
    to: '19.3'
  condition: []
  action:
  - data:
      message: Its getting warmer
      title: '{{now().strftime(''%H:%M:%S'')}}'
    service: notify.mypush
