- id: heal_zwave_network
  alias: Heal Z-Wave Network
  initial_state: 'on'
  trigger:
    platform: time
    at: '2:31:00'
  action:
    service: zwave.heal_network
- id: '2581929098159'
  alias: Turn on thread lights upstairs on motion
  trigger:
  - entity_id: binary_sensor.top_stairs_sensor,binary_sensor.bookcase_sensor_sensor
    platform: state
    to: 'on'
  condition:
  - after: '18:30'
    before: 07:30
    condition: time
  action:
  - data:
      entity_id:
      - switch.nano_switch_tread_upstairs_switch
    service: switch.turn_on
  - data:
      entity_id: timer.upstairs_lights
    service: timer.start
- id: 8e5370bbab674497ba5e26ca311f42d5
  alias: Turn off upstairs lights after timer
  trigger:
  - event_data:
      entity_id: timer.upstairs_lights
    event_type: timer.finished
    platform: event
  action:
  - data:
      entity_id:
      - switch.nano_switch_tread_upstairs_switch
    service: switch.turn_off
- id: '8681929098159'
  alias: Turn on downstairs thread lights on motion
  trigger:
  - entity_id: binary_sensor.middle_stairs_top
    platform: state
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-03:00:00'
      - condition: numeric_state
        entity_id: sensor.dark_sky_cloud_coverage
        above: 50
  action:
  - data:
      entity_id:
      - switch.downstairs_treadlight
      - switch.laundry_lights
    service: switch.turn_on
  - data:
      entity_id: timer.downstairs_tread_lights
    service: timer.start
- id: '1584550244601'
  alias: Turn scullery lights on
  trigger:
  - entity_id: binary_sensor.scullery_sensor_sensor
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id:
      - switch.scullery_dimmer_switch
    service: switch.turn_on
  - data: {}
    entity_id: timer.scullery
    service: timer.start
- id: '1584673132132'
  alias: Turn scullery light off after timer
  description: turns off the lights based on the configured timer
  trigger:
  - event_data:
      entity_id: timer.scullery
    event_type: timer.finished
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: switch.scullery_dimmer_switch
    service: switch.turn_off
- id: '1584743474579'
  alias: Turn off mid level tread lights after timer
  description: ''
  trigger:
  - event_data:
      entity_id: timer.downstairs_tread_lights
    event_type: timer.finished
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: switch.downstairs_treadlight
    service: switch.turn_off
- id: '1585953925794'
  alias: Start Garage Timer after switch is turned on
  description: ''
  trigger:
  - entity_id: light.garage_dimmer_level
    platform: state
    to: 'on'
  condition: []
  action:
  - data: {}
    entity_id: timer.garage_lights
    service: timer.start
- id: '1585996411514'
  alias: Turn Off Garage Lights after Timer
  description: ''
  trigger:
  - event_data:
      entity_id: timer.garage_lights
    event_type: timer.finished
    platform: event
  condition: []
  action:
  - data: {}
    entity_id: switch.garage_dimmer_switch
    service: switch.turn_off
